# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181204_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='所属团队'),
        ),
    ]
