# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190212_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='个人头像'),
        ),
    ]
