# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postion',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='为了节省存储资源，图片采取了字节流的方式保存在数据库中,在这里上传无法生效', upload_to='', verbose_name='个人头像'),
        ),
    ]
