# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, verbose_name='发生日期')),
                ('create_time', models.TimeField(blank=True, verbose_name='发生时间')),
                ('action_time', models.TimeField(blank=True, verbose_name='响应时间')),
                ('position_time', models.TimeField(blank=True, verbose_name='定位时间')),
                ('question_result', models.CharField(blank=True, default=None, max_length=125, null=True, verbose_name='问题进展')),
                ('question_memo', models.TextField(blank=True, default=None, null=True, verbose_name='问题简述')),
                ('question_reason', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='问题原因')),
                ('question_range', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='问题影响范围')),
            ],
            options={
                'verbose_name': '问题信息',
                'verbose_name_plural': '问题信息',
            },
        ),
    ]
