# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('ctime', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], default=1)),
                ('solution', models.TextField(null=True)),
                ('ptime', models.DateTimeField(null=True)),
                ('pingjia', models.IntegerField(choices=[(1, '不满意'), (2, '一般'), (3, '活很好')], default=2, null=True)),
                ('processer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='questionrecord',
            options={'verbose_name': '问题记录', 'verbose_name_plural': '问题记录'},
        ),
        migrations.AlterField(
            model_name='questionrecord',
            name='action_time',
            field=models.TimeField(auto_now=True, verbose_name='响应时间'),
        ),
        migrations.AlterField(
            model_name='questionrecord',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='发生日期'),
        ),
        migrations.AlterField(
            model_name='questionrecord',
            name='create_time',
            field=models.TimeField(auto_now_add=True, verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='questionrecord',
            name='position_time',
            field=models.TimeField(auto_now=True, verbose_name='定位时间'),
        ),
    ]
