# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_record', '0002_auto_20181128_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_question',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
