# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_record', '0003_auto_20181128_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_question',
            name='pingjia',
            field=models.IntegerField(choices=[(1, '不满意'), (2, '一般'), (3, '工作很赞')], default=2, null=True),
        ),
    ]
