# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-01 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '同意'), (1, '拒绝'), (2, '需额外审批人审批'), (3, '待处理')], verbose_name='审批状态')),
                ('comment', models.TextField(default=None, max_length=1024, verbose_name='审批意见')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('extra_parties', models.ManyToManyField(blank=True, related_name='related_parties', to=settings.AUTH_USER_MODEL, verbose_name='额外审批人列表')),
                ('flow', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workflows.Alter')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Step')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批用户')),
            ],
        ),
    ]
