# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_flowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrecord',
            name='comment',
            field=models.TextField(default=None, max_length=1024, null=True, verbose_name='审批意见'),
        ),
    ]
