# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_auto_20190211_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter',
            name='alter_status',
            field=models.SmallIntegerField(choices=[(0, '已提交'), (1, '已关闭'), (2, '被打回'), (3, '流程完成')], default=0, verbose_name='变更状态'),
        ),
    ]
