# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-12 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20190211_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_status',
            field=models.SmallIntegerField(choices=[(0, '环节未开始'), (1, '环节已结束')], default=0, verbose_name='环节状态'),
        ),
        migrations.AlterField(
            model_name='alter',
            name='alter_status',
            field=models.SmallIntegerField(choices=[(0, '已提交'), (1, '保存未提交'), (2, '被打回'), (3, '流程完成')], default=0, verbose_name='变更状态'),
        ),
        migrations.AlterField(
            model_name='alter',
            name='alter_type',
            field=models.SmallIntegerField(choices=[(0, '一般变更'), (1, '紧急变更'), (2, '特急变更')], default=None, verbose_name='变更类型'),
        ),
    ]
