# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-12 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_auto_20190212_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_status',
        ),
        migrations.AddField(
            model_name='flowrecord',
            name='step_status',
            field=models.SmallIntegerField(choices=[(0, '环节未开始'), (1, '环节已结束')], default=0, verbose_name='当前环节状态'),
        ),
    ]
