# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-12 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20190212_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
